### PR TITLE
Update script to upload model to HF

### PR DESCRIPTION
**Pull request by Wauplin**
The logic to upload a model to the Hugging Face Hub (introduced in https://github.com/pytorch/torchtune/pull/59) is not ideal. It is not necessary (and even less robust) to create a local git repo to push your changes (see why [here](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http)).  We have an upload guide [here](https://huggingface.co/docs/huggingface_hub/guides/upload) as well if interested.

This PR simplifies the logic to make it up to date with the latest changes in `huggingface_hub`. Also worth mentioning that a `huggingface-cli upload` command also exists to upload any file/folder to the Hub. The logic is pretty similar to the one here but more robust/more maintained. I let you decide what you prefer!

**Note:** I'm working at HF as a maintainer of the `huggingface_hub` library. Feel free to ping me anytime :)

**Disclaimer:** I haven't properly run the script myself locally.

### CODE REVIEW

**Comment by joecummings** [comment]
@Wauplin Thanks for the contribution! We're huge fans of the `huggingface_hub` library and really needed to clean this script up. I'll check out the links you provided and run the script locally.

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
Thank you! This script did indeed need some love

**Comment by joecummings** [comment]
I've confirmed that with the following command: 

```
python torchtune/_cli/hf_upload/upload.py --repo_id jrc/test --model_path <MODEL_PATH>
```

I am able to upload a trained model:
Screenshot 2024-04-12 at 5 02 57 PM

We'll likely refactor this a little more, but this is a great start. One nit: @Wauplin would you be able to grab the `HF_TOKEN` necessary for uploading as a default to the argument `--hf_token`? We do this with our [`download` command](https://github.com/pytorch/torchtune/blob/1ea75e599d1431cff9a855fb685e70c9cfc65ca4/torchtune/_cli/download.py#L70) and find it extremely helpful.

**Comment by Wauplin** [comment]
> I've confirmed that with the following command I am able to upload a trained model:

Great! Thanks for testing @joecummings :pray: 

> would you be able to grab the HF_TOKEN necessary for uploading as a default to the argument --hf_token? We do this with our [download command](https://github.com/pytorch/torchtune/blob/1ea75e599d1431cff9a855fb685e70c9cfc65ca4/torchtune/_cli/download.py#L70) and find it extremely helpful.

Actually the best way to handle this is to default to `None` which delegates the token handling to `huggingface_hub`. This is better since `huggingface_hub` is more robust is term of token management. It can retrieve the token either from `$HF_TOKEN`, from `~/.cache/huggingface/token` or from the secret vault in Google Colab.

**Comment by Wauplin** [comment]
> ```
> python torchtune/_cli/hf_upload/upload.py --repo_id jrc/test --model_path <MODEL_PATH>
> ```

Thinking twice about it, I do think it'd be best to get rid of this script in `torchtune` and instead showcase the `huggingface-cli upload` command in the readme. The logic is almost the same but `huggingface-cli upload` is more likely to be maintained in the future + is already widely used by the community. The equivalent for the upload script would be:

```
huggingface-cli upload jrc/test  <MODEL_FOLDER_PATH>
```

which will upload the entire directory in which your model is saved to a new repo on the Hub.

If you only want to upload the `README.md`, `LICENSE` and `.pth` files, you can do:

```
huggingface-cli upload jrc/test <MODEL_FOLDER_PATH> --include="README.md" --include="LICENSE" --include="*.pth"
```
Files that don't match any `--include` pattern will be ignored.

@msaroufim @joecummings WDYT?

**Comment by Wauplin** [comment]
> I see on the CLI [Getting Started](https://huggingface.co/docs/huggingface_hub/en/guides/cli#getting-started) guide that it's recommended to install some extra dependencies specific to the CLI

@joecummings no need for this extra dependencies no. It is only useful for `delete-cache` which is quite a corner case. I'll change the docs to mention it more explicitely that for 99% of the users, simply installing `huggingface_hub` is enough - so no need to worry about it :)

> torchtune already depends on huggingface_hub so the core CLI functionality should be already available for torchtune users.

Should we close this PR without merging then and open a new PR to delete this script + update README commands?

**Comment by Wauplin** [comment]
Thanks @joecummings, I'll review it. And closing this one as well now that it's not relevant anymore.

**Pull request closed without merging**
