### PR TITLE
New integration - CometLogger

### PR DESCRIPTION
**Pull request by Lothiraldan**
#### Context
This PR introduces support for logging metrics to Comet https://www.comet.com/site/.

#### Changelog
* Add `torchtune.utils.metric_logging.CometLogger`
* Add unit tests
* Update documentation and reference 

#### Test plan

- [x] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ x add unit tests for any new functionality
- [ ]xupdate docstrings for any new or updated methods or classes
- [x] run unit tests via `pytest tests`
- [x] run recipe tests via `pytest tests -m integration_test`

### CODE REVIEW

**Review by kartikayk — COMMENTED** [review]
@Lothiraldan thanks so much for the PR! Really excited about new community integrations. Do you mind sharing more context on why this logger is needed and what problem it solves?

Highlighting ecosystem integrations is one of the core principles of torchtune and something we believe makes the ecosystem stronger.

We started with integrations for WandB and Tensorboard since these have come up as feature requests in the user conversations we had. Generally, we'd like to get more user signal into different integrations before we move them to the core repo. 

Our general mode of operation is:

- Land integration in a fork
- Highlight the integration in the new community integration section we're adding to the README (PR should be up in a day or 2)
- As more folks look at this and we get requests to merge this into main, we can pull in this change

Let me know if this makes sense.

**Comment by sherpan** [comment]
Hi, Jumping in since @Lothiraldan is on PTO! My name is Sid and I'm a ML Growth Engineer at Comet. 

We opened the PR since we had two enterprise customers asking for it. They’re currently using Transformers and looking to switch to torchtune. We’re happy to connect them directly to the torchtune team if that helps.

 There’s >100k researchers using Comet on cloud and given how disruptive TorchTune is we expect a lot of them will want to switch but will be blocked. The rest of the core training frameworks usually define a logging Abstract Base Class and we create/maintain a Comet Subclass for logging metrics and assets to Comet. It’s worked well in the [Pytorch Lightning](https://github.com/Lightning-AI/pytorch-lightning/tree/master/src/lightning/pytorch/loggers), [Transformers](https://github.com/huggingface/transformers/blob/5b7a225f2502840f4066b1b39ef53411ea4d6e90/src/transformers/integrations/integration_utils.py#L937), [Composer libraries](https://github.com/mosaicml/composer/tree/dev/composer/loggers): all which have multiple logging options for users.

We could create a fork and ask our Comet users to go there but i think it adds another layer of complexity for our mutual users and customers.  Would really appreciate if you can consider a similar approach to other frameworks and happy to help on the implementation side.

**Comment by RdoubleA** [comment]
Hi @Lothiraldan, looks like we're seeing more user interest in CometLogger here #1221. Wondering if you're still open to landing this? if not, we may incorporate some of your additions here in the other PR. Let me know your thoughts.

**Comment by Lothiraldan** [comment]
Hi @RdoubleA, yes I'm still looking into landing this pull request. I took a quick look at the other PR and it seems roughly equivalent. Happy to help merging either one of the pull request.

**Comment by RdoubleA** [comment]
Let's converge on the other PR then. Do you mind reviewing it and working with @dzheng256 to get anything that is missing added (such as your excellent tutorial)? Really appreciate your work on this

**Comment by dzheng256** [comment]
Thanks for this PR @Lothiraldan, again apologies for basically recreating it, I had written an internal CometLogger we were using with torchtune already so I turned it into a PR but should have double checked for open PRs first.

**Comment by Lothiraldan** [comment]
@dzheng256 No worries at all, it's great that we had the same idea around the same time. I will incorporate few changes in your PR, it already looks pretty good!

**Pull request closed without merging**
