### PR TITLE
Update run.py to use runpy.run_path instead of runpy.run_module

### PR DESCRIPTION
**Pull request by psoulos**
In order to run a custom recipe from a local file, I needed to change this line.

#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [X] fix a bug
- [ ] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

#### Changelog
What are the changes made in this PR?
*

#### Test plan
Please make sure to do each of the following if applicable to your PR. If you're unsure about any one of these just ask and we will happily help. We also have a [contributing page](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md) for some guidance on contributing.

- [ ] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add [unit tests](https://github.com/pytorch/torchtune/tree/main/tests/torchtune) for any new functionality
- [ ] update [docstrings](https://github.com/pytorch/torchtune/tree/main/docs/source) for any new or updated methods or classes
- [ ] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

#### UX
If your function changed a public API, please add a dummy example of what the user experience will look like when calling it.
Here is a [docstring example](https://github.com/pytorch/torchtune/blob/6a7951f1cdd0b56a9746ef5935106989415f50e3/torchtune/modules/vision_transformer.py#L285)
and a [tutorial example](https://pytorch.org/torchtune/main/tutorials/qat_finetune.html#applying-qat-to-llama3-models)

- [ ] I did not change any public API
- [ ] I have added an example to docs or docstrings

### CODE REVIEW

**Review by joecummings — COMMENTED** [review]
I think this is correct, but @RdoubleA can you take a look?

**Comment by joecummings** [comment]
@psoulos Thanks for the PR! Would you mind signing the CLA so we can kick off our CI?

**Comment by RdoubleA** [comment]
Hi @psoulos, I've actually just fixed this so please install the latest nightlies (available by tomorrow) and try with the standard file path with slashes again, let me know if there's still issues.

**Comment by psoulos** [comment]
@RdoubleA I did not install the latest nightlies in order to not mess with my environment, but I did manually apply the change from #1760. I can confirm that using the dotpath with the current release version or the full path with the changes from #1760 works as expected. The only issue I ran into is that I placed my_custom_recipe.py in recipes/ which throws a ModuleNotFoundError because of recipes/__init__.py. It might be worth documenting that custom recipes should not be placed in recipes/

**Comment by RdoubleA** [comment]
> It might be worth documenting that custom recipes should not be placed in recipes/

Absolutely, this is on my radar. Thanks for testing and verifying both scenarios, nothing else needed from you. We can close this PR. See you around~

**Pull request closed without merging**
