### PR TITLE
[ez] add a clarification for first time users

### PR DESCRIPTION
**Pull request by skcoirz**
#### Context
- Users are required to download from meta website for the first time. Afterward, HF is available. (as explained in https://github.com/meta-llama/llama?tab=readme-ov-file#access-to-hugging-face)
- The example below is for HF. So clarify it a little bit for first time users.

#### Changelog
- updated readme.md with a clarification

#### Test plan
- check preview.

### CODE REVIEW

**Comment by SLR722** [comment]
For NUX, it seems users can directly request access from HF meta-llama page without going to meta website

**Comment by skcoirz** [comment]
> For NUX, it seems users can directly request access from HF meta-llama page without going to meta website

oh? I read it from meta website. Let me create a new HF account and try.

**Comment by skcoirz** [comment]
@SLR722 , tried with my new account. It failed at access check.

```
(torchtune) [huanwng@devgpu004]~/github/torchtune% tune download \
--repo-id meta-llama/Llama-2-7b \
--output-dir /tmp/llama2
Traceback (most recent call last):
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/meta-llama/Llama-2-7b/revision/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/huanwng/.conda/envs/torchtune/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/home/huanwng/github/torchtune/torchtune/_cli/tune.py", line 133, in main
    runpy.run_path(str(cmd), run_name="__main__")
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/huanwng/github/torchtune/torchtune/_cli/download.py", line 73, in <module>
    download(args.repo_id, args.output_dir, args.hf_token)
  File "/home/huanwng/github/torchtune/torchtune/_cli/download.py", line 34, in download
    snapshot_download(
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 255, in snapshot_download
    raise api_call_error
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 186, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2423, in repo_info
    return method(
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2233, in model_info
    hf_raise_for_status(r)
  File "/home/huanwng/.conda/envs/torchtune/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-6605d589-301c25f530e4b72d4a22bdab;56203e31-de06-458d-9857-60eab9c0a8f4)

Cannot access gated repo for url https://huggingface.co/api/models/meta-llama/Llama-2-7b/revision/main.
Access to model meta-llama/Llama-2-7b is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-2-7b to ask for access.



```

**Comment by RdoubleA** [comment]
@skcoirz this is not related to weights access, but with accessing external links from an internal server. try accessing this from your local machine. message me if you'd like to set it up for your internal server

**Comment by skcoirz** [comment]
tune download works now after HF admin approved my request. Learning
- the error is caused by HF Llama2 access control.
- There might be an auto acl sync between llama2 main site and HF (mentioned on the site)

**Pull request closed without merging**
