### PR TITLE
fix: lora dropout applied to all models

### PR DESCRIPTION
**Pull request by Optimox**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [x] fix a bug
- [ ] update tests and/or documentation
- [ ] other (please add here)

Related to issue #996 

#### Changelog
I only pass the `lora_dropout` argument where needed

#### Test plan
Please make sure to do each of the following if applicable to your PR. (If you're not sure about any one of these just ask and we will happily help.)

- [ ] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add unit tests for any new functionality
- [ ] update docstrings for any new or updated methods or classes
- [ ] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
	- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

### CODE REVIEW

**Comment by Optimox** [comment]
@ebsmothers yes you are right I forgot to update the mistral model! I've just added a new commit to take care of it!

**Comment by ebsmothers** [comment]
Ah sorry just a couple more output layers.. [here](https://github.com/pytorch/torchtune/blob/46d7c8313b55b9f5876e3194a057790021384f79/torchtune/models/phi3/_component_builders.py#L219), [here](https://github.com/pytorch/torchtune/blob/46d7c8313b55b9f5876e3194a057790021384f79/torchtune/models/llama2/_component_builders.py#L236), and [here](https://github.com/pytorch/torchtune/blob/46d7c8313b55b9f5876e3194a057790021384f79/torchtune/models/llama3/_component_builders.py#L233). After that I think this should be good to go!

**Comment by Optimox** [comment]
@ebsmothers good catch! updated!

**Review by ebsmothers — APPROVED** [review]
Looks good! Thanks again for catching and fixing this. Just kicked off CI, once it's green I can merge.

**Pull request merged**
