### PR TITLE
Add safe-serialization to FullModelHFCheckpointer

### PR DESCRIPTION
**Pull request by jeffrey-fong**
#### Context
What is the purpose of this PR? Is it to
- [x] add a new feature
- [ ] fix a bug
- [ ] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

As mentioned in #931, `FullModelHFCheckpointer` saves model checkpoints as .pt files, which is not entirely compatible with HuggingFace Transformers, specifically in Text-Generation Inference (TGI). As a step towards making this repo more compatible with HuggingFace libraries, I propose this PR which allows saving of model checkpoint directly as `safetensors`.

#### Changelog
In this PR, I added the option to save model checkpoints as `safetensors` checkpoint for `FullModelHFCheckpointer`. This will be done when the option `safe-serialization` is set to `True`. The option will default to `False` if it is set specifically or not set at all.

Example Config for checkpointer:
```yaml
checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Meta-Llama-3-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Meta-Llama-3-8B-Instruct/
  model_type: LLAMA3
  safe_serialization: True
resume_from_checkpoint: False
```

#### Test plan
Please make sure to do each of the following if applicable to your PR. (If you're not sure about any one of these just ask and we will happily help.)

- [x] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add unit tests for any new functionality
- [ ] update docstrings for any new or updated methods or classes
- [x] run unit tests via `pytest tests`
- [x] run recipe tests via `pytest tests -m integration_test`
- [x] manually run any new or modified recipes with sufficient proof of correctness
	- [x] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

### CODE REVIEW

**Comment by joecummings** [comment]
This is awesome, thanks @jeffrey-fong! Waiting for tests to pass, then I'll merge.

**Review by joecummings — APPROVED** [review]
🚀

**Comment by joecummings** [comment]
Looks like this was opened before #1095 was merged. Can you rebase?

**Comment by jeffrey-fong** [comment]
Sure it's done

**Pull request merged**
