### PR TITLE
Update API ref for torchtune/data

### PR DESCRIPTION
**Pull request by RdoubleA**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [ ] fix a bug
- [x] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

#### Changelog
- Include missing APIs in live docs
- Rename message converters to be less llama2 specific

#### Test plan
Please make sure to do each of the following if applicable to your PR. (If you're not sure about any one of these just ask and we will happily help.)

- [x] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add unit tests for any new functionality
- [x] update docstrings for any new or updated methods or classes
- [x] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
	- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

### CODE REVIEW

**Review by joecummings — COMMENTED** [review]
Can you add a 1-2 sentence blurb under each section with a description of what it is?

**Comment by RdoubleA** [comment]
> One thing that's a bit confusing to me on the data page is the relationship between "Chat Formats" and "Instruct Templates", if they're all just templates maybe they should be grouped together under text templates?

At this rate I might just combine them altogether...

**Comment by joecummings** [comment]
Commandeered this diff here: #1091

**Comment by joecummings** [comment]
Closed by #1091

**Pull request closed without merging**
