### PR TITLE
Latexifying IPOLoss docs

### PR DESCRIPTION
**Pull request by SalmanMohammadi**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [ ] fix a bug
- [x] update tests and/or documentation
- [ ] other (please add here)

image
I couldn't get big brackets working : (

### CODE REVIEW

**Comment by ebsmothers** [comment]
\bigl/\bigr -> \bigg? At least that's what I remember using back in the day

**Comment by SalmanMohammadi** [comment]
> \bigl/\bigr -> \bigg? At least that's what I remember using back in the day

You still got it man

**Review by ebsmothers — APPROVED** [review]
:math:`\frac{10}{10}`

**Comment by SalmanMohammadi** [comment]
image

**Pull request merged**
