### PR TITLE
Make AlpacaToMessage public.

### PR DESCRIPTION
**Pull request by krammnic**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [X] fix a bug
- [X] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

#### Changelog
What are the changes made in this PR?
* Make AlpacaToMessage public.
#1769 

#### Test plan
Please make sure to do each of the following if applicable to your PR. If you're unsure about any one of these just ask and we will happily help. We also have a [contributing page](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md) for some guidance on contributing.

- [X] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add [unit tests](https://github.com/pytorch/torchtune/tree/main/tests/torchtune) for any new functionality
- [ ] update [docstrings](https://github.com/pytorch/torchtune/tree/main/docs/source) for any new or updated methods or classes
- [ ] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

#### UX
If your function changed a public API, please add a dummy example of what the user experience will look like when calling it.
Here is a [docstring example](https://github.com/pytorch/torchtune/blob/6a7951f1cdd0b56a9746ef5935106989415f50e3/torchtune/modules/vision_transformer.py#L285)
and a [tutorial example](https://pytorch.org/torchtune/main/tutorials/qat_finetune.html#applying-qat-to-llama3-models)

- [ ] I did not change any public API
- [X] I have added an example to docs or docstrings

Really minor fix. This code is now working:

```
from torchtune.datasets import AlpacaToMessages

message_transform = AlpacaToMessages(
    train_on_input=True, column_map=None
)
```

### CODE REVIEW

**Comment by krammnic** [comment]
@joecummings @RdoubleA Require review.

**Review by joecummings — APPROVED** [review]
Thanks for this!

**Comment by krammnic** [comment]
Oh, some strange problem with docs, let me fix

**Comment by krammnic** [comment]
I see, should have added in `data/__init__.py`

**Comment by krammnic** [comment]
@joecummings I found out the problem. AlpacaToMessages should be moved to torchtune.data by analogy to other Transforms, it should no be included in datasets if it is public(I don't know how it happened that is is not with other transforms but in alpaca_dataset).

**Comment by RdoubleA** [comment]
@krammnic @joecummings thanks for pointing this out. Let's move `AlpacaToMessages` to `torchtune/data/_messages.py` where the other message transforms live.

**Comment by krammnic** [comment]
New example, if changing API:

```
from torchtune.data._messages import AlpacaToMessages

message_transform = AlpacaToMessages(
    train_on_input=True, column_map=None
)
```

We probably can don't care about legacy, because previously it was internal.

**Comment by krammnic** [comment]
@joecummings  @RdoubleA You can check new changes

**Comment by RdoubleA** [comment]
Docs look good. just need to fix lint by running: `pre-commit run --all-files`

**Comment by krammnic** [comment]
> Docs look good. just need to fix lint by running: `pre-commit run --all-files`

Runned it and pushed. I hope now is fine.

**Comment by krammnic** [comment]
Probably can be merged, lint checks passed.

**Pull request merged**
