### PR TITLE
Set drop_last to always True

### LINKED ISSUE #1754: drop_last does not work with `ConcatDataset`
`drop_last` is expected to be specified with the dataset config object, but this errors out when you use multiple datasets and cfg_dataset becomes a ListConfig: https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_distributed.py#L511

Possible fixes:
- Always use `drop_last=True`
- Explicitly check for ListConfig, if so just use True

### PR DESCRIPTION
**Pull request by RdoubleA**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [x] fix a bug
- [ ] update tests and/or documentation
- [ ] other (please add here)

Closes #1754. Instead of specifying drop_last with the dataset config (which will break when passed into the dataset builder), just hardcode to True. No configs expose this. We can make it configurable down the line if users request it.

#### Test plan
CI

### CODE REVIEW

**Review by acisseJZhong — APPROVED** [review]

**Review by ebsmothers — CHANGES_REQUESTED** [review]
Is this the right fix? Personally I find a top-level config field called `drop_last` to be pretty unclear. Why not just infer `drop_last` in the existing if/else for `ConcatDataset` here? https://github.com/pytorch/torchtune/blob/main/recipes/full_finetune_distributed.py#L487-L496

E.g. 

```
if isinstance(cfg_dataset, ListConfig):
  # same stuff as before
  drop_last = any([single_cfg_dataset.get("drop_last", True) for single_cfg_dataset in cfg_dataset])
else:
  # same stuff as before
  drop_last = cfg_dataset.get("drop_last", True)
```

**Comment by RdoubleA** [comment]
drop_last being in the dataset config does not make sense, as dataset points to a component and all heaths should be related to that component/builder. drop_last is not in any of our dataset builders. I think having it top level is less confusing in that sense.

Frankly, we should have a more configurable dataloader or a section in the config for dataloader args, as this is becoming more customized.

**Comment by ebsmothers** [comment]
OK yeah it is a dataloader config more than a dataset config so I do see your point there. Mainly I just do not want us to wind up with a hodgepodge of a bunch of random top-level configs, and `drop_last` is too in the weeds for the majority of users to care about (it is pretty much the exact definition of an edge case).

**Review by joecummings — COMMENTED** [review]
Rather than trying to conceive of edge cases that users might not even care about, can we just default drop_last to True, document it, and then *if* users want to have this be configurable, we can add a config. 

Either way it's a one line change. For most cases, the last batch should be dropped.

**Comment by RdoubleA** [comment]
Agreed

**Review by ebsmothers — APPROVED** [review]

**Pull request merged**
