### PR TITLE
SFT dataset - model transform validation

### PR DESCRIPTION
**Pull request by andrewldesousa**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [ ] fix a bug
- [ ] update tests and/or documentation
- [x] other (improve engineering practices and raising value errors for bad transforms)

Please link to any issues this PR addresses.
https://github.com/pytorch/torchtune/issues/1326

#### Changelog
What are the changes made in this PR?
Raise value error and unit tests for this code path

#### Test plan
Please make sure to do each of the following if applicable to your PR. (If you're not sure about any one of these just ask and we will happily help. We also have a [contributing page](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md) for some guidance on contributing.)

- [x] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [x] add [unit tests](https://github.com/pytorch/torchtune/tree/main/tests/torchtune) for any new functionality
- [x] update [docstrings](https://github.com/pytorch/torchtune/tree/main/docs/source) for any new or updated methods or classes
- [x] run unit tests via `pytest tests`
- [x] run recipe tests via `pytest tests -m integration_test`
- [x] manually run any new or modified recipes with sufficient proof of correctness
- [x] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

#### UX
If your function changed a public API, please add a dummy example of what the user experience will look like when calling it.
Example of docstring: https://github.com/pytorch/torchtune/blob/6a7951f1cdd0b56a9746ef5935106989415f50e3/torchtune/modules/vision_transformer.py#L285
Example in our docs: https://pytorch.org/torchtune/main/tutorials/qat_finetune.html#applying-qat-to-llama3-models

- [x] I did not change any public API;
- [ ] I have added an example to docs or docstrings;

### CODE REVIEW

**Comment by andrewldesousa** [comment]
cc: @joecummings @RdoubleA

**Comment by felipemello1** [comment]
hey @andrewldesousa , thanks for the PR! A few questions:

1. Is this the only dataset that needs it? For example, why not add it to the instructdataset https://github.com/pytorch/torchtune/blob/71ea1d236af1821611c1faed57e6ea7f3c7f1ea6/torchtune/datasets/_instruct.py#L122

2. The if condition may break if the output is not an iterable (you are checking if "key" in X). Should we first confirm that the output is a dictionary?

3. In the error message, to help with debugging, should we output the keys found?

**Comment by andrewldesousa** [comment]
> hey @andrewldesousa , thanks for the PR! A few questions:
> 
> 1. Is this the only dataset that needs it?
> 2. The if condition may break if the output is not an iterable (you are checking if "key" in X). Should we first confirm that the output is a dictionary?
> 3. In the error message, to help with debugging, should we output the keys found?

1. For validating model transform, yes. There is a potential opportunity to validate the same keys returned by PackedDataset if that is valuable to do, but i think that should be considered a separate issue if it is even an issue at all.
2. I think _either approach here is viable_, but I think that 1) the same issue occurs in the message_transform call above and through various parts of the code base. it might add more friction to developers to here to type check every similar situation but of course this is open to discussion. 2) its fine to rely on users here to use the SFTDataset correctly and implement valid transforms which adhere to the Transform spec given there is fairly clear documentation for what is expected of the user. 3) the datasets in this repos that will leverage this class are should be protected against this issue from code review and testing

**Review by felipemello1 — APPROVED** [review]
lgtm

**Review by RdoubleA — APPROVED** [review]
Thanks for covering this and adding a test. Just need to fix lint and we can merge

**Pull request merged**
