### PR TITLE
Delete unused APIs

### PR DESCRIPTION
**Pull request by rohan-varma**
#### Context
- All these APIs are unused by our recipes. If they do end up providing value later on, we can always add them back.

#### Changelog
- removed get_autocast, get_gradient_scaler, wrap_fsdp and tests for them.

#### Test plan
- CI

### CODE REVIEW

**Comment by ebsmothers** [comment]
Very happy to see this PR. CI is red though

**Comment by ebsmothers** [comment]
@rohan-varma what's happening with this PR?

**Comment by joecummings** [comment]
Are these in docs?

**Comment by rohan-varma** [comment]
@joecummings They aren't in docs. @ebsmothers Thanks for pinging, just updated

**Review by ebsmothers — APPROVED** [review]
Once CI is green it looks good to me. Thanks for cleaning these up!

**Pull request merged**
