### PR TITLE
Update API ref for torchtune/data

### PR DESCRIPTION
**Pull request by joecummings**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [ ] fix a bug
- [x] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

#### Changelog
What are the changes made in this PR?

#### Test plan
Please make sure to do each of the following if applicable to your PR. (If you're not sure about any one of these just ask and we will happily help.)

- [ ] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add unit tests for any new functionality
- [x] update docstrings for any new or updated methods or classes
- [ ] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
	- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

### CODE REVIEW

**Comment by ebsmothers** [comment]
A couple comments:

1) Why are there no examples for any of the template/format classes? Imo these benefit the most from a simple example (reading the current API docs I have no idea what's going on), and they are the easiest to document (literally just copy the existing format string into the docstring and throw in some example text).
2) CROSS_ENTROPY_IGNORE_IDX is technically an undocumented public API. (Why is it a public API though?)

**Comment by joecummings** [comment]
> 2. CROSS_ENTROPY_IGNORE_IDX is technically an undocumented public API. (Why is it a public API though?)

We use `CROSS_ENTROPY_IGNORE_IDX` in our recipes, therefore we need to have it be a public API.

**Review by RdoubleA — APPROVED** [review]
Thanks for finishing this up, if you haven't already do you mind linking the other PR and closing that one?

**Comment by joecummings** [comment]
> Thanks for finishing this up, if you haven't already do you mind linking the other PR and closing that one?

This RST drove me insane.

**Pull request merged**
