### PR TITLE
Fix max_seq_len for llama 3 70b

### PR DESCRIPTION
**Pull request by musab-mk**
Fixes the default max_seq_len to 8192

### CODE REVIEW

**Review by kartikayk — COMMENTED** [review]
Thanks so much for the fix! Mind signing the CLA and then I can accept and merge.

**Comment by joecummings** [comment]
Can you do this for `lora_llama3_70b` as well?

**Review by rohan-varma — COMMENTED** [review]
Thanks! As @joecummings, please fix the default in `lora_llama3_70b` as well. then we can approve CI and merge!

**Comment by musab-mk** [comment]
@rohan-varma Done

**Review by ebsmothers — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
