### PR TITLE
Add filter_fn to all generic dataset classes and builders API

### PR DESCRIPTION
**Pull request by krammnic**
#### Context
What is the purpose of this PR? Is it to add filter_fn to all required dataset builders APIs and generics.
- [ ] add a new feature
- [X] fix a bug
- [X] update tests and/or documentation
- [ ] other (please add here)

Please link to any issues this PR addresses.

#### Changelog
What are the changes made in this PR?
1. filter_fn to all required generic dataset classes according to #1768 
2. filter_fn in all specific dataset builders(usually based on SFTDataset) API update
3. docstrings update

#### Test plan
Please make sure to do each of the following if applicable to your PR. If you're unsure about any one of these just ask and we will happily help. We also have a [contributing page](https://github.com/pytorch/torchtune/blob/main/CONTRIBUTING.md) for some guidance on contributing.

- [X] run pre-commit hooks and linters (make sure you've first installed via `pre-commit install`)
- [ ] add [unit tests](https://github.com/pytorch/torchtune/tree/main/tests/torchtune) for any new functionality
- [X] update [docstrings](https://github.com/pytorch/torchtune/tree/main/docs/source) for any new or updated methods or classes
- [ ] run unit tests via `pytest tests`
- [ ] run recipe tests via `pytest tests -m integration_test`
- [ ] manually run any new or modified recipes with sufficient proof of correctness
- [ ] include relevant commands and any other artifacts in this summary (pastes of loss curves, eval results, etc.)

#### UX
If your function changed a public API, please add a dummy example of what the user experience will look like when calling it.
Here is a [docstring example](https://github.com/pytorch/torchtune/blob/6a7951f1cdd0b56a9746ef5935106989415f50e3/torchtune/modules/vision_transformer.py#L285)
and a [tutorial example](https://pytorch.org/torchtune/main/tutorials/qat_finetune.html#applying-qat-to-llama3-models)

- [ ] I did not change any public API
- [X] I have added an example to docs or docstrings

I'm not sure about all changes, so review is very glad here. 

I have might missed something so added [WIP].

### CODE REVIEW

**Comment by krammnic** [comment]
@RdoubleA @joecummings Require accurate review

**Comment by RdoubleA** [comment]
This looks great. Could you also add it to the multimodal datasets?

**Comment by krammnic** [comment]
> This looks great. Could you also add it to the multimodal datasets?

Done.

**Comment by krammnic** [comment]
Revised.

**Comment by krammnic** [comment]
@RdoubleA Probably now is fine(fixed linting and docs was building on previous revisions). I have 3 PR-s opened yet, but let's start from here.

**Comment by krammnic** [comment]
@RdoubleA Finnaly!

**Review by RdoubleA — APPROVED** [review]

**Pull request merged**
