### PR TITLE
added extra check in __del__

### PR DESCRIPTION
**Pull request by felipemello1**
#### Context
What is the purpose of this PR? Is it to
- [ ] add a new feature
- [x] fix a bug
- [ ] update tests and/or documentation
- [ ] other (please add here)

see https://github.com/pytorch/torchtune/issues/1298 for context

#### Changelog
just add extra check

### CODE REVIEW

**Comment by joecummings** [comment]
> Going to be annoying - can you confirm correct error is raised when wandb isn't installed, please? Or add a unit test? : )

One of us!!!!

**Comment by felipemello1** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by felipemello1** [comment]
@joecummings @SalmanMohammadi  good call :P fixed it

image

**Review by joecummings — APPROVED** [review]
STAMP

**Pull request merged**
